version: 2
executorType: machine
stages:
  build:
    workDir: ~/ghostscript-deb
    steps:
      - type: shell
        name: Prep /development
        command: |
          sudo mkdir /development
          sudo chmod 777 /development
          ln -s /home/circleci/ghostscript-deb /development/ghostscript-deb
      - type: checkout
      - type: shell
        name: Build image
        command: |
          cd trusty
          docker-compose build
          docker-compose run ghostscript
      - type: shell
        name: Show tree
        command: sudo apt-get install -y tree && tree
      - type: shell
        name: Upload package
        command: aws s3 cp ~/ghostscript-deb/trusty/out/ghostscript_9.21-trusty-talis2_amd64.deb s3://aspire-operations/binaries/aptly/trusty/ghostscript_9.21-trusty-talis2_amd64.deb

